version: "3.9"

services:
  backend:
    build: .
    container_name: slots-backend
    environment:
      LOG_LEVEL: info
    ports:
      - "8080:8080"
      - "9091:9091"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/healthz"]
      interval: 15s
      timeout: 3s
      retries: 3
